version: '2.3'
services:
  webapp:
    image: xppay-demo
    volumes:
      - web-assets:/usr/src/static
      - web-media:/usr/src/media
    environment:
      DISCORD_OAUTH_KEY:
      DISCORD_OAUTH_SECRET:
      DISCORD_REDIRECT_IS_HTTPS:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
    depends_on:
      - database
  webserver:
    image: nginx
    volumes:
      - ./support/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - web-assets:/usr/src/static:ro
      - web-media:/usr/src/media:ro
    depends_on:
      - webapp
  database:
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    command:
      ["--character-set-server=utf8mb4",
       "--collation-server=utf8mb4_unicode_ci"]

volumes:
  web-assets:
  web-media:
  db-data:
