version: '2.3'
services:
  webapp:
    build:
      context: .
    image: xppay-demo
    volumes:
      - web-assets:/usr/src/static
      - web-media:/usr/src/media
  webserver:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - web-assets:/usr/src/static:ro
      - web-media:/usr/src/media:ro
    depends_on:
      - webapp

volumes:
  web-assets:
  web-media:
