version: '2.3'
services:
  webapp:
    environment:
      DISCORD_OAUTH_KEY:
      DISCORD_OAUTH_SECRET:
      DISCORD_REDIRECT_IS_HTTPS: 1
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
    networks:
      - front-tier
      - backend-tier
    labels:
      - "traefik.enable=false"
  webserver:
    networks:
      - front-tier
      - traefik-tier
    labels:
      - "traefik.backend=webserver"
      - "traefik.frontend.rule=Host:labo.xppay.jp"
      - "traefik.frontend.passHostHeader=true"
  proxy:
    image: traefik:1.5-alpine
    command:
      ["-c", "/traefik.toml"]
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./support/docker/traefik/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - proxy-certs:/etc/traefik/acme
    networks:
      - traefik-tier
    labels:
      - "traefik.enable=false"
  database:
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - backend-tier
    labels:
      - "traefik.enable=false"

volumes:
  web-media:
    driver_opts:
      type: none
      device: /var/xppay-demo/media
      o: bind
  proxy-certs:
    driver_opts:
      type: none
      device: /var/xppay-demo/certs
      o: bind
  db-data:
    driver_opts:
      type: none
      device: /var/xppay-demo/mariadb
      o: bind

networks:
  front-tier:
  traefik-tier:
  backend-tier:
