version: '2.3'
services:
  webapp:
    build:
      context: .
    environment:
      DISCORD_OAUTH_KEY:
      DISCORD_OAUTH_SECRET:
      DISCORD_REDIRECT_IS_HTTPS:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
  webserver:
    ports:
      - 80:80
  database:
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
