# Generated by Django 2.0.1 on 2018-02-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.CharField(max_length=255, verbose_name='表示名')),
                ('url', models.URLField(max_length=2000, verbose_name='Webhook URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='使用中')),
            ],
        ),
    ]
