# Generated by Django 2.0.2 on 2018-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XpJpyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_jpy', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='1XPのJPYでの価格')),
                ('last_updated', models.DateTimeField(verbose_name='最終更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'get_latest_by': 'last_updated',
            },
        ),
    ]
