# Generated by Django 2.0.1 on 2018-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_discord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Discordでの名前'),
        ),
    ]
