# Generated by Django 2.0.1 on 2018-02-16 05:46

from django.db import migrations


def copy_in_qrcode(apps, schema_editor):
    Shop = apps.get_model('shops', 'Shop')
    for shop in Shop.objects.all():
        for approval in shop.approvals.all():
            approval.in_qrcode = shop.in_qrcode
            approval.save(update_fields=['in_qrcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopapproval_in_qrcode'),
    ]

    operations = [migrations.RunPython(copy_in_qrcode, reverse_code=migrations.RunPython.noop)]
