# Generated by Django 2.0.1 on 2018-02-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20180201_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='map_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
