# Generated by Django 2.0.1 on 2018-02-05 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180204_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_order', models.IntegerField()),
                ('origin', models.ImageField(upload_to='shops/origin/%y/%m/%d')),
            ],
            options={
                'ordering': ['list_order'],
            },
        ),
        migrations.AlterField(
            model_name='benefit',
            name='content',
            field=models.CharField(max_length=200, verbose_name='特典内容'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了日時'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address1',
            field=models.CharField(max_length=100, verbose_name='住所1'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='shops.Area', verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business_description',
            field=models.CharField(max_length=1000, verbose_name='紹介文'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='map_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='店舗地図URL'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='zipcode',
            field=models.CharField(help_text='ハイフンを入れず7桁の数字で入力してください', max_length=7, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='photo',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
    ]
