# Generated by Django 2.0.1 on 2018-02-16 06:01

from django.db import migrations


def restore_in_qrcode(apps, schema_editor):
    Shop = apps.get_model('shops', 'Shop')
    for shop in Shop.objects.all():
        approval = shop.approvals.filter(in_qrcode__isnull=False).order_by('-pk').first()
        if approval:
            shop.in_qrcode = approval.in_qrcode
            shop.save(update_fields=['in_qrcode'])


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180216_1446'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=restore_in_qrcode),
        migrations.RemoveField(
            model_name='shop',
            name='in_qrcode',
        ),
    ]
