# Generated by Django 2.0.1 on 2018-02-16 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0004_remove_shop_in_qrcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together={('shop', 'staff')},
        ),
    ]
