# Generated by Django 2.0.1 on 2018-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20180205_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='list_order',
        ),
        migrations.AlterField(
            model_name='photo',
            name='origin',
            field=models.ImageField(help_text='PCでは画像ファイルをファイルボタンにドラッグすると簡単に指定できます', upload_to='shops/origin/%y/%m/%d', verbose_name='店舗画像'),
        ),
    ]
