# Generated by Django 2.0.1 on 2018-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20180206_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='URLで店舗を識別するための単語を指定します', null=True, verbose_name='スラッグ'),
        ),
    ]
