# Generated by Django 2.0.1 on 2018-02-23 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shops.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0005_auto_20180217_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='招待コード')),
                ('expired_at', models.DateTimeField(default=shops.models.expires_default, editable=False, verbose_name='有効期限')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='招待日時')),
                ('accepted_at', models.DateTimeField(null=True, verbose_name='招待日時')),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='招待者')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='招待者')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='shops.Shop')),
            ],
        ),
    ]
