# Generated by Django 2.0.1 on 2018-02-06 09:19

from django.db import migrations


def name_to_slug(apps, schema_editor):
    Shop = apps.get_model('shops', 'Shop')
    for shop in Shop.objects.all():
        shop.slug = shop.name.replace(' ', '-')
        shop.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_slug'),
    ]

    operations = [
        migrations.RunPython(name_to_slug, reverse_code=migrations.RunPython.noop)
    ]
