# Generated by Django 2.0.1 on 2018-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_staffinvitation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shopapproval',
            index=models.Index(fields=['approved'], name='shops_shopa_approve_5414bd_idx'),
        ),
    ]
