# Generated by Django 2.0.1 on 2018-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20180206_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='discord_for_payment',
            field=models.CharField(default='@', help_text='XPpayでの支払先に使用するDiscordアカウント名を指定します', max_length=100, verbose_name='支払先Discordアカウント'),
        ),
        migrations.AddField(
            model_name='shop',
            name='in_qrcode',
            field=models.CharField(blank=True, help_text='PDF内に表示するQRコードに埋め込む文字列を指定します', max_length=2000, verbose_name='QRコード用文字列'),
        ),
    ]
