# Generated by Django 2.0.1 on 2018-02-13 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0009_auto_20180208_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('canceled_at', models.DateTimeField(null=True, verbose_name='取り下げ・取消日時')),
                ('approved', models.CharField(choices=[('RE', '申請済み'), ('EX', '審査中'), ('AP', '承認'), ('DE', '否認')], default='RE', max_length=2, verbose_name='承認結果')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('canceled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_approvals', to=settings.AUTH_USER_MODEL, verbose_name='取消者')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shop_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shop_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.ContactType', verbose_name='連絡方法'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='href',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='リンク'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='label',
            field=models.CharField(max_length=100, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='list_order',
            field=models.IntegerField(help_text='数値の低い方が優先されます', verbose_name='表示優先順'),
        ),
        migrations.AddField(
            model_name='shopapproval',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='shopapproval',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_approvals', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
    ]
