# Generated by Django 2.0.1 on 2018-02-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20180213_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopapproval',
            options={'permissions': (('can_approve', 'Can approve shop'),)},
        ),
    ]
